
package Vista;

import AccesosDatos.alumnoData;
import Entidades.Alumno;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author deborahhhh
 */
public class vistaAlumno extends javax.swing.JInternalFrame {
    private alumnoData aluData = new alumnoData();
    private Alumno alumActual = null;
    private List<Alumno> alumnos = new ArrayList<>();

    public vistaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JB_nuevo = new javax.swing.JButton();
        JB_eliminar = new javax.swing.JButton();
        JB_baja = new javax.swing.JButton();
        txtDNI = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        JB_actualizar = new javax.swing.JButton();
        JB_buscar = new javax.swing.JButton();
        jB_agregar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jB_mostrar = new javax.swing.JButton();
        jB_alta = new javax.swing.JButton();
        jD_nac = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Formulario Alumnos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Documento:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Estado:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");

        JB_nuevo.setText("Nuevo");
        JB_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_nuevoActionPerformed(evt);
            }
        });

        JB_eliminar.setText("Eliminar");
        JB_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_eliminarActionPerformed(evt);
            }
        });

        JB_baja.setText("Baja");
        JB_baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_bajaActionPerformed(evt);
            }
        });

        JB_actualizar.setText("Actualizar");
        JB_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_actualizarActionPerformed(evt);
            }
        });

        JB_buscar.setText("Buscar");
        JB_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_buscarActionPerformed(evt);
            }
        });

        jB_agregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\54266\\Downloads\\iconos_netbeans\\iconos netbeans\\icons8-agregar-administrador-80.png")); // NOI18N
        jB_agregar.setText("Agregar");
        jB_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agregarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ID:");

        jB_mostrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\54266\\Downloads\\iconos_netbeans\\iconos netbeans\\icons8-mostrar-propiedad-64.png")); // NOI18N
        jB_mostrar.setText("Mostrar");
        jB_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_mostrarActionPerformed(evt);
            }
        });

        jB_alta.setText("Alta");
        jB_alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_altaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jD_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtapellido)
                                            .addComponent(txtnom)
                                            .addComponent(txtDNI)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtid)
                                                .addGap(147, 147, 147)))))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jB_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(JB_nuevo)
                                .addGap(18, 18, 18)
                                .addComponent(JB_buscar)
                                .addGap(18, 18, 18)
                                .addComponent(JB_actualizar)
                                .addGap(18, 18, 18)
                                .addComponent(JB_eliminar)
                                .addGap(21, 21, 21)
                                .addComponent(JB_baja)
                                .addGap(18, 18, 18)
                                .addComponent(jB_alta)))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jB_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jD_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_nuevo)
                    .addComponent(JB_buscar)
                    .addComponent(JB_actualizar)
                    .addComponent(JB_eliminar)
                    .addComponent(JB_baja)
                    .addComponent(jB_alta))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_actualizarActionPerformed
      
        JB_actualizar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarAlumno();
            }
        });
   
    }//GEN-LAST:event_JB_actualizarActionPerformed

    private void jB_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agregarActionPerformed
        
        jB_agregar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                agregarAlumno();
            }
        });
        
    }//GEN-LAST:event_jB_agregarActionPerformed

    private void JB_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_nuevoActionPerformed
        
        JB_nuevo.addActionListener(e -> nuevoAlumno());
        
    }//GEN-LAST:event_JB_nuevoActionPerformed

    private void JB_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_buscarActionPerformed
      
        JB_buscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarAlumnoPorId();
            }
        });
    }//GEN-LAST:event_JB_buscarActionPerformed

    private void JB_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_eliminarActionPerformed
        
        JB_eliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                eliminarAlumno();
            }
        });
        
    }//GEN-LAST:event_JB_eliminarActionPerformed

    private void jB_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_mostrarActionPerformed
        
         jB_mostrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mostrarAlumnos();
            }
        });
    }//GEN-LAST:event_jB_mostrarActionPerformed

    private void JB_bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_bajaActionPerformed
        
        JB_baja.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                bajaAlumno();
            }
        });
        
    }//GEN-LAST:event_JB_bajaActionPerformed

    private void jB_altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_altaActionPerformed
        
        jB_alta.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                altaAlumno();
            }
        });
    }//GEN-LAST:event_jB_altaActionPerformed
    
    private void agregarAlumno() {
        int idAlumno = Integer.parseInt(txtid.getText());
        int dni = Integer.parseInt(txtDNI.getText());
        String nombre = txtnom.getText();
        String apellido = txtapellido.getText();
        LocalDate fechaNacimiento = LocalDate.parse(jD_nac.getDateFormatString());
        boolean estado = true;

        aluData.guardarAlumno(new Alumno(idAlumno, dni, nombre, apellido, fechaNacimiento, estado));
        JOptionPane.showMessageDialog(null, "Alumno agregado: " + nombre + " " + apellido);
        limpiarCampos();
    }
    
    private void buscarAlumnoPorId() {
        int idAlumno = Integer.parseInt(txtDNI.getText());
        for (Alumno alumno : alumnos) {
            if (alumno.getIdAlumno()== idAlumno) {
            JOptionPane.showMessageDialog(null, "Alumno encontrado: " + alumno.getNombre() + " " + alumno.getApellido());    
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Alumno no encontrado");
    }

    private void nuevoAlumno() {
    // Habilitar los campos de entrada
        txtDNI.setEnabled(true);
        txtnom.setEnabled(true);
        txtapellido.setEnabled(true);
        jD_nac.setEnabled(true);
        
        limpiarCampos();
        
        JB_nuevo.setEnabled(true);
    }
    
     private void actualizarAlumno() {
        int dni = Integer.parseInt(txtDNI.getText());
        for (Alumno alumno : alumnos) {
            if (alumno.getDni() == dni) {
                alumno.setNombre(txtnom.getText());
                alumno.setApellido(txtapellido.getText());
                alumno.setfechaNacimiento(LocalDate.parse(jD_nac.getDateFormatString()));
                JOptionPane.showMessageDialog(null, "Alumno modificado: " + alumno.getNombre() + " " + alumno.getApellido());
                limpiarCampos();
                return;
            }
        }
     }    
    private void eliminarAlumno() {
        try {
            int dni = Integer.parseInt(txtDNI.getText().trim());
            aluData.borrarAlumnoPorId(dni);
            JOptionPane.showMessageDialog(null, "Alumno " + dni + " eliminado.");
           
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, " Por favor ingrese un DNI valido.");     
        }
     }   
    
    private void bajaAlumno() {
        int dni = Integer.parseInt(txtDNI.getText());
        for (Alumno alumno : alumnos) {
            if (alumno.getDni() == dni) {
                alumno.setActivo(false);
                JOptionPane.showMessageDialog(null, "Alumno dado de baja: " + alumno.getNombre() + " " + alumno.getApellido());
                limpiarCampos();
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Alumno no encontrado."); 
    }
    
    private void altaAlumno() {
        int dni = Integer.parseInt(txtDNI.getText());
        for (Alumno alumno : alumnos) {
            if (alumno.getDni() == dni) {
                alumno.setActivo(true);
                JOptionPane.showMessageDialog(null, "Alumno dado de alta: " + alumno.getNombre() + " " + alumno.getApellido());
                limpiarCampos();
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Alumno no encontrado");
    }
    
    private void mostrarAlumnos() {
        JOptionPane.showMessageDialog(null, "Lista de Alumnos: ");
        for (Alumno alumno : alumnos) {
            JOptionPane.showMessageDialog(null, alumno.getIdAlumno() + " - " + alumno.getDni() + " - " + alumno.getNombre() + " - " + alumno.getApellido() + " - " + alumno.getFechaNacimiento() + " - " + (alumno.isActivo() ? "Activo" : "Inactivo"));
    }
    }
    
    private void limpiarCampos() {
        txtid.setText("");
        txtDNI.setText("");
        txtnom.setText("");
        txtapellido.setText("");
        jD_nac.setDate(null);
    }
       
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_actualizar;
    private javax.swing.JButton JB_baja;
    private javax.swing.JButton JB_buscar;
    private javax.swing.JButton JB_eliminar;
    private javax.swing.JButton JB_nuevo;
    private javax.swing.JButton jB_agregar;
    private javax.swing.JButton jB_alta;
    private javax.swing.JButton jB_mostrar;
    private com.toedter.calendar.JDateChooser jD_nac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
