/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Xethias
 */
public class vistaInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaInscripcion
     */
    public vistaInscripcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitulo = new javax.swing.JLabel();
        jlbSeleccione = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcbAlumno = new javax.swing.JComboBox<>();
        jlbListado = new javax.swing.JLabel();
        jrbInscripta = new javax.swing.JRadioButton();
        jrbNoinscripto = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMostaralumnos = new javax.swing.JTable();
        jbnInsertar = new javax.swing.JButton();
        jbnAñadirinscription = new javax.swing.JButton();
        jbnSalir = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbTitulo.setText("Formulario de Inscripcion");
        getContentPane().add(jlbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 217, -1));

        jlbSeleccione.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbSeleccione.setText("Seleccione un Alumno:");
        getContentPane().add(jlbSeleccione, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 55, 144, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 27, 362, 10));

        jcbAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 55, -1, -1));

        jlbListado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbListado.setText("Listado de Materias");
        getContentPane().add(jlbListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 134, 165, -1));

        jrbInscripta.setText(" Materias Inscriptas");
        jrbInscripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInscriptaActionPerformed(evt);
            }
        });
        getContentPane().add(jrbInscripta, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 95, -1, -1));

        jrbNoinscripto.setText("Materias No Inscriptas");
        getContentPane().add(jrbNoinscripto, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 95, -1, -1));

        jtbMostaralumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbMostaralumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 165, 375, 179));

        jbnInsertar.setText("Insertar");
        getContentPane().add(jbnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jbnAñadirinscription.setText("Añadir inscripción");
        getContentPane().add(jbnAñadirinscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jbnSalir.setText("Salir");
        getContentPane().add(jbnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbInscriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInscriptaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbInscriptaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbnAñadirinscription;
    private javax.swing.JButton jbnInsertar;
    private javax.swing.JButton jbnSalir;
    private javax.swing.JComboBox<String> jcbAlumno;
    private javax.swing.JLabel jlbListado;
    private javax.swing.JLabel jlbSeleccione;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JRadioButton jrbInscripta;
    private javax.swing.JRadioButton jrbNoinscripto;
    private javax.swing.JTable jtbMostaralumnos;
    // End of variables declaration//GEN-END:variables
}
